import Link from "next/link";

const city = "Piura";

export default function Home() {
  return <main>
    <nav className="nav"><Link className="brand" href="/">Geo Propiedades<span>Piura</span></Link><div className="navlinks"><Link href="#piura">Piura</Link><Link href="#estadisticas">Estadísticas</Link><Link href="#ayuda">Ayuda</Link></div><Link className="btn primary" href="/publicar">Publicar gratis</Link></nav>
    <section className="hero"><div><div className="eyebrow">Propiedades en un solo mapa interactivo</div><h1>Compra, alquila o vende en Piura.</h1><p>Encuentra casas, terrenos, departamentos y locales de Piura en un mapa interactivo. Busca por sector, compara zonas y conoce exactamente dónde está cada propiedad antes de contactar.</p><div className="actions"><Link className="btn primary" href="/explorar?ciudad=Piura">Explorar mapa de Piura</Link><Link className="btn ghost" href="/publicar">Publicar gratis ahora</Link></div></div><div className="map" aria-label="Mapa interactivo de propiedades en Piura"><div className="searchbar">⌕ Buscar en Piura por sector o dirección...</div><div className="pin">$98k</div></div></section>
    <section id="estadisticas" className="stats"><div className="stat"><b>1</b><span>Propiedad en Piura</span></div><div className="stat"><b>1</b><span>En venta</span></div><div className="stat"><b>0</b><span>En alquiler</span></div></section>
    <section id="piura" className="section"><h2>Piura en un solo lugar</h2><p>Explora propiedades disponibles en Piura sin abrir varios portales ni repetir la misma búsqueda.</p><div className="cards"><article className="card"><h3>Mapa de Piura</h3><p>Revisa casas, terrenos, departamentos y locales con su ubicación visible.</p><Link href="/explorar?ciudad=Piura">Ver mapa interactivo →</Link></article><article className="card"><h3>Cerca de ti</h3><p>Centra el mapa en tu ubicación dentro de Piura y encuentra opciones alrededor.</p><Link href="/explorar?ciudad=Piura">Buscar cerca de ti →</Link></article><article className="card"><h3>Ubicación clara</h3><p>Cada anuncio se entiende en el mapa: marcador, sector o polígono cuando aplica.</p><Link href="/explorar?ciudad=Piura">Ver propiedades →</Link></article></div></section>
    <section className="section"><h2>Propiedad destacada en Piura</h2><p>Anuncio con precio y ubicación en el mapa.</p><div className="cards"><article className="card"><div className="eyebrow">En venta</div><h3>Terreno urbano estratégico en Piura</h3><p>Piura · Terreno · 640 m²</p><Link href="/explorar?ciudad=Piura">Ver detalle →</Link></article></div></section>
    <section className="section"><h2>Explorar Piura</h2><div className="cities"><Link className="city" href="/explorar?ciudad=Piura">Piura</Link></div></section>
    <section className="cta"><div><h2>Publica gratis en Piura y recibe contactos directos.</h2><p>Tu anuncio aparece con fotos, precio, medidas y ubicación en el mapa.</p></div><Link className="btn" href="/publicar">Publicar gratis ahora</Link></section>
    <footer><span>Geo Propiedades Piura · Hecho en Perú 🇵🇪</span><span><Link href="/explorar?ciudad=Piura">Mapa de Piura</Link> · <Link href="/ayuda">Centro de ayuda</Link></span></footer>
  </main>;
}
