import Link from "next/link";

const cities = ["Quito","Guayaquil","Manta","Cuenca","Daule","Salinas","Playas","Santa Elena","Atacames","Durán","Punta Blanca","Ambato"];

export default function Home() {
  return <main>
    <nav className="nav"><Link className="brand" href="/">Geo Propiedades<span>Ecuador</span></Link><div className="navlinks"><Link href="#ciudades">Ciudades</Link><Link href="#estadisticas">Estadísticas</Link><Link href="#ayuda">Ayuda</Link></div><Link className="btn primary" href="/publicar">Publicar gratis</Link></nav>
    <section className="hero"><div><div className="eyebrow">Propiedades en un solo mapa interactivo</div><h1>Compra, alquila o vende sin perderte entre portales.</h1><p>Encuentra casas, terrenos, departamentos y locales en un mapa interactivo. Busca alrededor de ti, compara zonas reales y conoce exactamente dónde está cada propiedad antes de contactar.</p><div className="actions"><Link className="btn primary" href="/explorar">Explorar mapa completo</Link><Link className="btn ghost" href="/publicar">Publicar gratis ahora</Link></div></div><div className="map" aria-label="Mapa interactivo de propiedades"><div className="searchbar">⌕ Buscar por ciudad, sector o dirección...</div><div className="pin">$98k</div></div></section>
    <section id="estadisticas" className="stats"><div className="stat"><b>19.532</b><span>Propiedades</span></div><div className="stat"><b>19.360</b><span>En venta</span></div><div className="stat"><b>172</b><span>En alquiler</span></div></section>
    <section className="section"><h2>Un solo lugar</h2><p>Explora propiedades disponibles sin abrir varios portales ni repetir la misma búsqueda.</p><div className="cards"><article className="card"><h3>Un solo mapa</h3><p>Revisa casas, terrenos, departamentos y locales con su ubicación visible.</p><Link href="/explorar">Ver mapa interactivo →</Link></article><article className="card"><h3>Cerca de ti</h3><p>Centra el mapa en tu ubicación o ciudad y encuentra opciones alrededor.</p><Link href="/explorar">Buscar cerca de ti →</Link></article><article className="card"><h3>Ubicación clara</h3><p>Cada anuncio se entiende en el mapa: marcador, sector o polígono cuando aplica.</p><Link href="/explorar">Ver propiedades →</Link></article></div></section>
    <section className="section"><h2>Propiedades destacadas en el mapa</h2><p>Anuncios con foto, precio y ubicación en el mapa.</p><div className="cards"><article className="card"><div className="eyebrow">En venta</div><h3>Departamento Dúplex en Venta</h3><p>Quito, Pichincha · Departamento · 111 m²</p><Link href="/explorar">Ver detalle →</Link></article><article className="card"><div className="eyebrow">En venta</div><h3>Terreno de 1200 m² en Cochapamba</h3><p>Quito, Pichincha · Terreno · 1.200 m²</p><Link href="/explorar">Ver detalle →</Link></article><article className="card"><div className="eyebrow">En venta</div><h3>Casa en Urbanización San Antonio</h3><p>Samborondón, Guayas · Casa · 150 m²</p><Link href="/explorar">Ver detalle →</Link></article></div></section>
    <section id="ciudades" className="section"><h2>Principales ciudades</h2><div className="cities">{cities.map(city => <Link className="city" key={city} href={'/explorar?ciudad='+encodeURIComponent(city)}>{city}</Link>)}</div></section>
    <section className="cta"><div><h2>Publica gratis y recibe contactos directos.</h2><p>Tu anuncio aparece con fotos, precio, medidas y ubicación en el mapa.</p></div><Link className="btn" href="/publicar">Publicar gratis ahora</Link></section>
    <footer><span>Geo Propiedades Ecuador · Hecho en Ecuador 🇪🇨</span><span><Link href="/explorar">Mapa interactivo</Link> · <Link href="/ayuda">Centro de ayuda</Link></span></footer>
  </main>;
}
