"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { supabase } from "../lib/supabase";

const MAX_PHOTOS = 5;
const MAX_BYTES = 5 * 1024 * 1024;

export default function PublishPage() {
  const [status, setStatus] = useState("");
  const [coords, setCoords] = useState({ latitude: "-5.1945", longitude: "-80.6328" });
  const [files, setFiles] = useState<File[]>([]);
  function useLocation() { if (!navigator.geolocation) return setStatus("Este navegador no admite geolocalización."); setStatus("Obteniendo ubicación…"); navigator.geolocation.getCurrentPosition(({ coords: p }) => { setCoords({ latitude: p.latitude.toFixed(6), longitude: p.longitude.toFixed(6) }); setStatus("Ubicación obtenida."); }, () => setStatus("No se pudo obtener la ubicación. Puedes introducirla manualmente."), { enableHighAccuracy: true, timeout: 10000 }); }
  function onFiles(event: React.ChangeEvent<HTMLInputElement>) { const selected = Array.from(event.target.files ?? []); if (selected.length > MAX_PHOTOS) return setStatus(`Puedes subir un máximo de ${MAX_PHOTOS} fotos.`); if (selected.some((file) => !["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > MAX_BYTES)) return setStatus("Cada foto debe ser JPG, PNG o WebP y pesar como máximo 5 MB."); setFiles(selected); setStatus(""); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const latitude = Number(coords.latitude), longitude = Number(coords.longitude), price = Number(form.get("price")); if (!Number.isFinite(latitude) || !Number.isFinite(longitude) || latitude < -6 || latitude > -4 || longitude < -82 || longitude > -79) return setStatus("Indica coordenadas válidas dentro de Piura."); if (!files.length) return setStatus("Añade al menos una foto de la propiedad."); if (!supabase) return setStatus("Falta configurar NEXT_PUBLIC_SUPABASE_URL y NEXT_PUBLIC_SUPABASE_ANON_KEY en Railway."); setStatus("Publicando…"); const operation = String(form.get("operation") ?? "Vender"); const type = String(form.get("type") ?? "Terrenos"); const { data: property, error } = await supabase.from("properties").insert({ title: form.get("title"), listing_type: operation === "Alquilar" ? "rent" : "sale", property_type: type === "Casas" ? "house" : type === "Departamentos" ? "apartment" : "land", price, currency: "USD", description: form.get("description"), address: form.get("address"), city: "Piura", region: "Piura", lat: latitude, lng: longitude, status: "published" }).select("id").single(); if (error) { console.error("Error publishing property:", error); return setStatus("No pudimos publicar la propiedad. Inténtalo nuevamente."); } if (!property) return setStatus("No pudimos publicar la propiedad. Inténtalo nuevamente."); for (const [index, file] of files.entries()) { const storagePath = `${property.id}/${crypto.randomUUID()}-${file.name}`; const upload = await supabase.storage.from("property-images").upload(storagePath, file, { contentType: file.type, upsert: false }); if (upload.error) return setStatus(`No se pudo guardar la foto ${index + 1}.`); const { data: publicFile } = supabase.storage.from("property-images").getPublicUrl(storagePath); const imageInsert = await supabase.from("property_images").insert({ property_id: property.id, storage_path: storagePath, public_url: publicFile.publicUrl, sort_order: index, is_cover: index === 0 }); if (imageInsert.error) return setStatus(`No se pudo registrar la foto ${index + 1}.`); } setStatus("Propiedad publicada. El marcador aparecerá al volver al mapa."); event.currentTarget.reset(); setFiles([]); }
  return <main className="publish-page"><Link href="/" className="back-link">← Volver al mapa</Link><p className="eyebrow">PUBLICA GRATIS · PIURA</p><h1>Publica tu propiedad</h1><p className="publish-intro">Completa los datos, indica la ubicación y añade fotos para mostrar tu inmueble en el mapa.</p><form onSubmit={submit} className="publish-form"><label>Tipo de propiedad<select name="type" required><option value="Terrenos">Terreno</option><option value="Casas">Casa</option><option value="Departamentos">Departamento</option></select></label><label>Operación<select name="operation" required><option value="Vender">Vender</option><option value="Alquilar">Alquilar</option></select></label><label>Título del anuncio<input name="title" required placeholder="Ej. Terreno residencial en Castilla" /></label><label>Precio en USD<input name="price" type="number" min="1" required placeholder="72000" /></label><label>Descripción<textarea name="description" required rows={4} placeholder="Describe las características principales…" /></label><label>Dirección o sector<input name="address" required placeholder="Castilla, Piura" /></label><fieldset><legend>Ubicación de coordenadas</legend><div className="coordinate-grid"><label>Latitud<input value={coords.latitude} onChange={(e) => setCoords({ ...coords, latitude: e.target.value })} inputMode="decimal" required /></label><label>Longitud<input value={coords.longitude} onChange={(e) => setCoords({ ...coords, longitude: e.target.value })} inputMode="decimal" required /></label></div><button type="button" className="location-btn" onClick={useLocation}>Usar mi ubicación actual</button><small>También puedes ajustar las coordenadas manualmente. Se validan para Piura.</small></fieldset><label>Fotos de la propiedad<input type="file" accept="image/jpeg,image/png,image/webp" multiple required onChange={onFiles} /><small>Obligatorio: 1 a 5 fotos · JPG, PNG o WebP · máximo 5 MB por foto.</small>{files.length > 0 && <small>{files.length} foto(s) seleccionada(s).</small>}</label><button className="publish-submit" type="submit">Publicar propiedad</button>{status && <p className="form-status" role="status">{status}</p>}</form></main>;
}
